// Types for Clikio

export interface Address {
  street: string;
  locality: string;
  province: string;
  location: { lat: number; lng: number };
}

export interface User {
  id: string;
  email: string;
  username: string;
  avatar?: string;
  isAdmin: boolean;
  address?: Address;
  dni: string;
  phone?: string;
  createdAt: Date;
}

export interface Auction {
  id: string;
  createdBy: string;
  title: string;
  description: string;
  images: string[];
  startingPrice: number;  // ← DEBE ser startingPrice
  currentPrice: number;
  buyNowPrice?: number;
  startTime: Date;
  endTime: Date;
  status: 'active' | 'ended' | 'sold' | 'cancelled' | 'scheduled';
  categoryId: string;
  bids: Bid[];
  winnerId?: string;
  featured?: boolean;
  isFlash?: boolean;
  condition?: 'new' | 'like-new' | 'excellent' | 'good' | 'fair';
  stickers?: string[]; // Stickers para hacer más atractivo
  createdAt?: Date;
  unitsPerBundle?: number; // Unidades por bulto (uxb)
  bundles?: number; // Cantidad de bultos disponibles
  sellOnlyByBundle?: boolean; // Si es true, solo se puede vender por bulto completo
  // Relación opcional con un producto de la tienda (para reportes / stock compartido)
  linkedProductId?: string;
  isMystery?: boolean; // Si es true, la subasta es misteriosa (oculta imagen y título hasta que finalice)
  auctionType?: 'normal' | 'featured' | 'flash' | 'combo' | 'nocturnal' | 'special'; // Tipo de subasta para banners/plantillas
  comboProducts?: ComboProduct[]; // Productos incluidos en el combo (solo para tipo 'combo')
}

export interface ComboProduct {
  productId: string; // ID del producto de la tienda
  productName: string; // Nombre del producto (copia para referencia rápida)
  quantity: number; // Cantidad de este producto en el combo
  productImage?: string; // Imagen del producto (opcional, para mostrar en el combo)
}

export interface Bid {
  id: string;
  auctionId: string;
  userId: string;
  username: string;
  amount: number;
  createdAt: Date;
  isBot?: boolean;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  images: string[];
  price: number;
  stock: number;
  // Stock total histórico (cantidad inicial); stock es el disponible actual
  stockTotal?: number;
  categoryId: string;
  ratings: Rating[];
  averageRating: number;
  badges?: string[];
  stickers?: string[]; // Stickers para hacer más atractivo
  active?: boolean;
  featured?: boolean;
  createdAt?: string;
  updatedAt?: string;
  unitsPerBundle?: number; // Unidades por bulto (uxb)
  bundles?: number; // Cantidad de bultos disponibles
  sellOnlyByBundle?: boolean; // Si es true, solo se puede vender por bulto completo
}

export interface Rating {
  userId: string;
  username: string;
  rating: number;
  comment: string;
  createdAt: Date;
}

export interface ProductReview {
  id: string;
  orderId: string;
  productId: string;
  productName: string;
  productImage?: string;
  userId: string;
  username: string;
  rating: number;
  comment: string;
  createdAt: Date;
}

export interface CartItem {
  productId: string;
  product: Product;
  quantity: number;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export interface Message {
  id: string;
  conversationId: string; // ID único por conversación (admin-userId)
  fromUserId: string;
  fromUsername: string;
  toUserId: string; // 'admin' o userId
  content: string;
  read: boolean;
  createdAt: Date;
  relatedAuctionId?: string;
  relatedProductId?: string;
  relatedOrderId?: string;
  isAutoGenerated?: boolean; // Si es mensaje automático del sistema
  type?: MessageType; // Tipo de mensaje para categorización
  priority?: MessagePriority; // Prioridad del mensaje
}

export type ConversationStatus = 'open' | 'closed';
export type MessagePriority = 'high' | 'medium' | 'low';
export type MessageType = 'chat' | 'contact' | 'help' | 'ticket';

export interface Conversation {
  id: string;
  userId: string;
  username: string;
  userAvatar?: string;
  lastMessage?: Message;
  unreadCount: number;
  updatedAt: Date;
  status?: ConversationStatus; // 'open' | 'closed'
  priority?: MessagePriority; // 'high' | 'medium' | 'low'
  type?: MessageType; // 'chat' | 'contact' | 'help' | 'ticket'
  closedAt?: Date;
  closedBy?: string; // 'admin' | userId
  reopenedAt?: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type:
    | 'auction_won'
    | 'auction_outbid'
    | 'purchase'
    | 'payment_reminder'
    | 'new_message'
    | 'order_shipped'
    | 'order_delivered'
    | 'order_expired'
    | 'ticket_updated';
  title: string;
  message: string;
  read: boolean;
  createdAt: Date;
  readAt?: Date | string;
  link?: string;
}

export interface NotificationRule {
  id: string;
  name: string;
  eventType:
    | 'auction_won'
    | 'auction_outbid'
    | 'purchase'
    | 'payment_reminder'
    | 'new_message'
    | 'order_shipped'
    | 'order_delivered'
    | 'order_expired'
    | 'ticket_updated';
  title: string;
  message: string;
  link?: string;
  active: boolean;
  isSystemRule?: boolean; // Indica si es una regla del sistema (no se puede eliminar)
  conditions?: {
    minAmount?: number;
    maxAmount?: number;
    userRoles?: ('user' | 'admin')[];
    productTypes?: ('auction' | 'store')[];
  };
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export interface Bot {
  id: string;
  name: string;
  balance: number;
  intervalMin: number;
  intervalMax: number;
  maxBidAmount: number;
  minIncrement?: number; // Incremento mínimo por oferta (por defecto 500)
  isActive: boolean;
  targetAuctions: string[];
  createdAt?: Date | string;
  updatedAt?: Date | string;
}

export type Theme = 'light' | 'dark' | 'experimental';

// ========== SISTEMA DE PEDIDOS (ACTUALIZADO) ==========

export type OrderStatus = 
  | 'pending_payment'      // Esperando pago (48hs para subastas)
  | 'payment_expired'      // Expiró el plazo de pago
  | 'payment_confirmed'    // Pago confirmado
  | 'processing'           // Procesando pedido (AGREGADO)
  | 'preparing'            // Preparando envío
  | 'shipped'              // Enviado (AGREGADO)
  | 'in_transit'           // En camino
  | 'delivered'            // Entregado
  | 'cancelled'            // Cancelado
  | 'expired';             // Expiró el plazo de pago (alternativo)

export type ProductType = 'store' | 'auction';

export type DeliveryMethod = 'shipping' | 'pickup' | 'email';

export interface ShippingAddress {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country?: string;
}

export interface Order {
  id: string;
  orderNumber?: string;           // Número único de pedido (tipo factura/remito)
  userId: string;
  userName: string;
  productId: string;
  productName: string;
  productImage: string;
  productType: ProductType;
  type: ProductType;              // Alias para compatibilidad
  amount: number;
  quantity?: number;              // Cantidad de productos en el pedido
  status: OrderStatus;
  paymentMethod?: 'mercadopago' | 'bank_transfer' | 'cash_on_delivery';
  deliveryMethod: DeliveryMethod;  // AGREGADO
  couponCode?: string;
  discountAmount?: number;
  createdAt: Date;
  paidAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
  expiresAt?: Date;               // Para subastas: fecha límite de pago (48hs)
  trackingNumber?: string;
  notes?: string;
  address: Address;
  shippingAddress?: ShippingAddress; // AGREGADO para compatibilidad con AdminPanel
  unitsPerBundle?: number;        // NUEVO: Unidades por bulto del producto
  bundles?: number;               // NUEVO: Bultos del producto al momento del pedido
  // Datos adicionales para transferencias bancarias
  bankAccountId?: string;
  bankAccountAlias?: string;
  bankAccountCbu?: string;
  paymentProofUrl?: string;
  paymentVerificationStatus?: 'pending' | 'approved' | 'rejected';
}

// Interfaz para el log de transacciones
export interface OrderTransaction {
  id: string;
  orderId: string;
  orderNumber: string;
  userId: string;
  userName: string;
  status: OrderStatus;
  amount: number;
  timestamp: string;
  date: string;                   // Formato: YYYY-MM-DD
  time: string;                   // Formato: HH:mm:ss
  actionType: 'created' | 'status_changed' | 'payment_received' | 'shipped' | 'delivered' | 'cancelled';
  previousStatus?: OrderStatus;
  newStatus?: OrderStatus;
  notes?: string;
  adminId?: string;
  adminName?: string;
}

export interface Report {
  totalSales: number;
  totalRevenue: number;
  pendingPayments: number;
  inTransit: number;
  delivered: number;
  cancelled: number;
  avgDeliveryTime: number;
  topSellingProducts: { id: string; name: string; sales: number }[];
}

// ========== SISTEMA DE ENVÍOS ==========

export type ShipmentStatus =
  | 'pending'        // Creado, esperando preparación
  | 'preparing'      // Preparando paquete
  | 'ready_to_ship'  // Listo para despachar
  | 'in_transit'     // En camino
  | 'delayed'        // Con demora
  | 'delivered'      // Entregado
  | 'returned'       // Devuelto
  | 'cancelled';     // Envío cancelado

export interface Shipment {
  id: string;
  orderId: string;
  userId: string;
  userName: string;
  status: ShipmentStatus;
  carrier?: string;
  trackingNumber?: string;
  trackingUrl?: string;
  // Copia de datos relevantes de la orden para acceso rápido
  productId: string;
  productName: string;
  productImage?: string;
  quantity?: number;
  deliveryMethod: DeliveryMethod;
  address: Address;
  notes?: string;
  createdAt: Date | string;
  updatedAt?: Date | string;
  shippedAt?: Date | string;
  deliveredAt?: Date | string;
}

// ========== SISTEMA DE TICKETS / CENTRO DE AYUDA ==========

export type TicketStatus = 'visto' | 'revision' | 'resuelto';

export type TicketType = 'consulta' | 'problema' | 'reembolso' | 'tecnico' | 'otro';

export interface Ticket {
  id: string;
  ticketNumber: string; // Número único de ticket (ej: TKT-2025-001)
  userId: string; // ID del usuario (puede ser null si no está registrado)
  userName: string;
  userEmail: string;
  userPhone?: string;
  type: TicketType;
  subject: string;
  message: string;
  status: TicketStatus;
  adminResponse?: string;
  adminId?: string; // ID del admin que respondió
  adminName?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  resolvedAt?: Date | string;
  priority?: 'baja' | 'media' | 'alta';
  relatedOrderId?: string;
  relatedAuctionId?: string;
  attachments?: string[]; // URLs de archivos adjuntos
}

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  phone: string;
  subject: string;
  message: string;
  createdAt: Date | string;
  read: boolean;
  readAt?: Date | string;
  adminResponse?: string;
}

// ========== SISTEMA DE CALENDARIO ==========

export type CalendarEventType = 
  | 'auction_start'      // Inicio de subasta
  | 'auction_end'         // Finalización de subasta
  | 'purchase'            // Compra de producto
  | 'campaign'            // Campaña promocional
  | 'event'               // Evento personalizado
  | 'order_delivery'      // Entrega de pedido
  | 'campaign_start'      // Inicio de campaña
  | 'campaign_end';       // Fin de campaña

export interface CalendarEvent {
  id: string;
  title: string;
  description?: string;
  type: CalendarEventType;
  startDate: Date | string;
  endDate?: Date | string; // Opcional para eventos de un solo día
  color?: string; // Color personalizado para el evento
  isAutomatic?: boolean; // Si es true, se genera automáticamente y no se puede editar/borrar manualmente
  relatedAuctionId?: string;
  relatedOrderId?: string;
  relatedProductId?: string;
  createdBy?: string; // ID del admin que creó el evento (si no es automático)
  createdAt?: Date | string;
  updatedAt?: Date | string;
}