// Types for Subasta Argenta

export interface Address {
  street: string;
  locality: string;
  province: string;
  location: { lat: number; lng: number };
}

export interface User {
  id: string;
  email: string;
  username: string;
  avatar?: string;
  isAdmin: boolean;
  address?: Address;
  dni: string;
  phone?: string;
  createdAt: Date;
}

export interface Auction {
  id: string;
  createdBy: string;
  title: string;
  description: string;
  images: string[];
  startingPrice: number;  // ← DEBE ser startingPrice
  currentPrice: number;
  buyNowPrice?: number;
  startTime: Date;
  endTime: Date;
  status: 'active' | 'ended' | 'sold' | 'cancelled' | 'scheduled';
  categoryId: string;
  bids: Bid[];
  winnerId?: string;
  featured?: boolean;
  isFlash?: boolean;
  condition?: 'new' | 'like-new' | 'excellent' | 'good' | 'fair';
  stickers?: string[]; // Stickers para hacer más atractivo
  createdAt?: Date;
}

export interface Bid {
  id: string;
  auctionId: string;
  userId: string;
  username: string;
  amount: number;
  createdAt: Date;
  isBot?: boolean;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  images: string[];
  price: number;
  stock: number;
  categoryId: string;
  ratings: Rating[];
  averageRating: number;
  badges?: string[];
  stickers?: string[]; // Stickers para hacer más atractivo
  active?: boolean;
  featured?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface Rating {
  userId: string;
  username: string;
  rating: number;
  comment: string;
  createdAt: Date;
}

export interface CartItem {
  productId: string;
  product: Product;
  quantity: number;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export interface Message {
  id: string;
  conversationId: string; // ID único por conversación (admin-userId)
  fromUserId: string;
  fromUsername: string;
  toUserId: string; // 'admin' o userId
  content: string;
  read: boolean;
  createdAt: Date;
  relatedAuctionId?: string;
  relatedProductId?: string;
  relatedOrderId?: string;
  isAutoGenerated?: boolean; // Si es mensaje automático del sistema
}

export interface Conversation {
  id: string;
  userId: string;
  username: string;
  userAvatar?: string;
  lastMessage?: Message;
  unreadCount: number;
  updatedAt: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type: 'auction_won' | 'auction_outbid' | 'purchase' | 'payment_reminder' | 'new_message';
  title: string;
  message: string;
  read: boolean;
  createdAt: Date;
  link?: string;
}

export interface Bot {
  id: string;
  name: string;
  balance: number;
  intervalMin: number;
  intervalMax: number;
  maxBidAmount: number;
  isActive: boolean;
  targetAuctions: string[];
}

export type Theme = 'light' | 'dark';

// ========== SISTEMA DE PEDIDOS (ACTUALIZADO) ==========

export type OrderStatus = 
  | 'pending_payment'      // Esperando pago (48hs para subastas)
  | 'payment_expired'      // Expiró el plazo de pago
  | 'payment_confirmed'    // Pago confirmado
  | 'processing'           // Procesando pedido (AGREGADO)
  | 'preparing'            // Preparando envío
  | 'shipped'              // Enviado (AGREGADO)
  | 'in_transit'           // En camino
  | 'delivered'            // Entregado
  | 'cancelled'            // Cancelado
  | 'expired';             // Expiró el plazo de pago (alternativo)

export type ProductType = 'store' | 'auction';

export type DeliveryMethod = 'shipping' | 'pickup' | 'email';

export interface ShippingAddress {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country?: string;
}

export interface Order {
  id: string;
  userId: string;
  userName: string;
  productId: string;
  productName: string;
  productImage: string;
  productType: ProductType;
  type: ProductType;              // Alias para compatibilidad
  amount: number;
  status: OrderStatus;
  paymentMethod?: string;
  deliveryMethod: DeliveryMethod;  // AGREGADO
  createdAt: Date;
  paidAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
  expiresAt?: Date;               // Para subastas: fecha límite de pago (48hs)
  trackingNumber?: string;
  notes?: string;
  address: Address;
  shippingAddress?: ShippingAddress; // AGREGADO para compatibilidad con AdminPanel
}

export interface Report {
  totalSales: number;
  totalRevenue: number;
  pendingPayments: number;
  inTransit: number;
  delivered: number;
  cancelled: number;
  avgDeliveryTime: number;
  topSellingProducts: { id: string; name: string; sales: number }[];
}
